// <auto-generated />
namespace M0v1n.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class logar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logar));
        
        string IMigrationMetadata.Id
        {
            get { return "201903192348250_logar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
