// <auto-generated />
namespace M0v1n.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testando : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testando));
        
        string IMigrationMetadata.Id
        {
            get { return "201903242142327_testando"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
