// <auto-generated />
namespace M0v1n.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class xyz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xyz));
        
        string IMigrationMetadata.Id
        {
            get { return "201903290239557_xyz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
