// <auto-generated />
namespace M0v1n.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mooviin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mooviin));
        
        string IMigrationMetadata.Id
        {
            get { return "201903180145240_mooviin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
